apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: cacdotnet
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/week8demo-293819/cacdotnet/nhs-webapp:latest
        name: cacdotnet
        env:
          - name: PORT
            value: "80"
        ports:
        - containerPort: 80
